### ISSUE TITLE
Failed to compile on STM32F413 with IAR

### ISSUE THREAD

**Issue by torontlhz** [jedisct1/libhydrogen#100]
want to porting libhydrogen to STM32F413 with IAR compiler, failed to compile, It says unsupported platform. 

Error[Pe020]: identifier "EINVAL" is undefined C:\Projects\..\LIBS\libhydrogen\impl\core.h 107 
Fatal Error[Pe035]: #error directive: Unsupported platform C:\Projects\..\LIBS\libhydrogen\impl\random.h 25 

any suggestion?
Thanks.

**Comment by jedisct1** [comment]
As the error message says, this is an unsupported platform :)

You can implement support for its entropy sources based on what's already in `impl/random`.

`EINVAL` not being defined is a different issue, may requiring some additional compilation flags.

I don't have the hardware nor the development environment, so you're on your own, sorry :)
