### ISSUE TITLE
Kindly requesting to introduce a determinist variant of  hydro_secretbox_keygen

### ISSUE THREAD

**Issue by pavlos-christoforou** [jedisct1/libhydrogen#101]
There is a hydro_sign_keygen_deterministic() API and would be nice to have a similar API for hydro_secretbox_keygen() (unless of course there are reasons not to).  It is low priority for us as we can do this at a higher level but thought it may be useful to report it.

**Comment by jedisct1** [comment]
This is a symmetric key. No other key is derived from it. Just fill it directly.

A `hydro_secretbox_deterministic_keygen()` would do nothing but copy the input bytes directly.
