### ISSUE TITLE
hydro_random_init() get called twice

### ISSUE THREAD

**Issue by DeeFuse** [jedisct1/libhydrogen#111]
I noticed `hydro_random_init()` get called from [`hydro_init()`](https://github.com/jedisct1/libhydrogen/blob/d4792dbb0ce1a627a29c162ad6d47296cf3cc47c/impl/core.h#L2) as well as in the first call to a random number function through [`hydro_random_check_initialized()`](https://github.com/jedisct1/libhydrogen/blob/d4792dbb0ce1a627a29c162ad6d47296cf3cc47c/impl/random.h#L31)

`hydro_init()` does not set `hydro_random_context.initialized` to 1
but `hydro_random_check_initialized()` is calling [`hydro_random_init()`](https://github.com/jedisct1/libhydrogen/blob/d4792dbb0ce1a627a29c162ad6d47296cf3cc47c/impl/random.h#L34) again and sets the necessary bits afterwards.

One possible solution would be to set  `hydro_random_context.initialized` to 1 `hydro_random_init()` or even in `hydro_init()`

**Comment by jedisct1** [comment]
Good catch, thank you!

> One possible solution would be to set hydro_random_context.initialized to 1 hydro_random_init() or even in hydro_init()

Done!
