### ISSUE TITLE
Sealed boxes support!

### ISSUE THREAD

**Issue by calvin2021y** [jedisct1/libhydrogen#113]
Is hydrogen able to provide Sealed boxes like libsodium ?

**Comment by jedisct1** [comment]
It certainly does.

Use the [N variant](https://github.com/jedisct1/libhydrogen/wiki/N-variant) of the key exchange system to get an ephemeral key to encrypt your data with.

Then, send the resulting packet and the encrypted data to the server, which will be able to decrypt it using its secret key.

**Comment by jedisct1** [comment]
This is even better than libsodium's sealed boxes since it supports an optional pre-shared key.
