### ISSUE TITLE
Flipping bit in secret key doesn't change results?

### ISSUE THREAD

**Issue by alemariusnexus** [jedisct1/libhydrogen#117]
I'm sure it's not a bug, but I've written a small test program that I expect to fail, but weirdly it doesn't, and that concerns me a bit. It's the following:

```c++
int main(int argc, char** argv)
{
    hydro_init();

    hydro_kx_keypair permKeys;
    hydro_kx_keygen(&permKeys);

    uint8_t packet[hydro_kx_N_PACKET1BYTES];

    // Derive some session keys
    hydro_kx_session_keypair sessKeys;
    hydro_kx_n_1(&sessKeys, packet, nullptr, permKeys.pk);

    // Original plaintext
    const char* plain = "Hello World!";

    // Encrypt symmetrically
    size_t cipherLen = hydro_secretbox_HEADERBYTES + strlen(plain);
    uint8_t* cipher = new uint8_t[cipherLen];
    hydro_secretbox_encrypt(cipher, plain, strlen(plain), 0, "testtest", sessKeys.tx);

    // Allocate memory for decryption
    char* decPlain = new char[strlen(plain)+1];
    hydro_memzero(decPlain, strlen(plain));
    decPlain[strlen(plain)] = '\0';

    // Throw away the old session keys
    hydro_memzero(&sessKeys, sizeof(sessKeys));

    // Flip one bit in the secret key
    permKeys.sk[0] ^= 1;

    // Decrypt ciphertext
    hydro_kx_n_2(&sessKeys, packet, nullptr, &permKeys);
    hydro_secretbox_decrypt(decPlain, cipher, cipherLen, 0, "testtest", sessKeys.rx);

    printf("Decrypted plaintext: %s\n", decPlain);

    delete[] cipher;
    delete[] decPlain;

    return 0;
}
```

It just encrypts and decrypts a message with keys generated by the N-variant kx functions, throwing them away and recalculating them between the two steps. But crucially, I flip one bit of the secret key before running `hydro_kx_n_2()` with it. I expected this to fail, but it quite happily succeeds and prints the original plaintext.

Is that how it's supposed to be? I have no background in cryptography, but I thought flipping even a single bit should change the encryption result completely. Is that bit not part of the actual key being used? Am I doing something wrong?

**Comment by jedisct1** [comment]
The 3 lower bits of the secret scalar are ignored, to avoid small subgroup confinement attacks by making it always a multiple of 8.

So, unless you get the same result by flipping higher bits, there's nothing to worry about.
