### ISSUE TITLE
What does hydro_hash_hash return, and under what conditions?

### ISSUE THREAD

**Issue by kozross** [jedisct1/libhydrogen#124]
Based on [the documentation here](https://github.com/jedisct1/libhydrogen/wiki/Generic-hashing#usage), `hydro_hash_hash` returns an `int`. However, it is not specified what this `int` will be, and under what conditions. Is this specified somewhere?

**Comment by kozross** [comment]
Thanks! What about all the other `int`-returning functions dealing with generic hashing? Is it the same kind of idea?

**Comment by jedisct1** [comment]
`0` means that everything's fine and `-1` that something went wrong :) Same convention everywhere, just like the C standard library.
