### ISSUE TITLE
Unable to compile random.h on a teensy chip

### ISSUE THREAD

**Issue by edubois** [jedisct1/libhydrogen#17]
```
Temp\arduino_build_987748\sketch\impl/random.h:35:5: error: 'MCUSR' undeclared (first use in this function)

     MCUSR = 0;


```
I'm pretty new on Arduino, is there a library I'm missing or any inclusion?

**Comment by edubois** [comment]
I would maybe suggest using https://github.com/pmjdebruijn/Arduino-Entropy-Library/blob/master/Entropy.h

as an entropy generator.

**Comment by jedisct1** [comment]
Unfortunately, the license is incompatible.

**Comment by edubois** [comment]
Ok, thanks for your answer, is there anything else I could do?

**Comment by jedisct1** [comment]
This will be in the next release for sure :)

**Comment by edubois** [comment]
Thanks!
