### ISSUE TITLE
Encryption with public key then decryption with private key

### ISSUE THREAD

**Issue by edubois** [jedisct1/libhydrogen#18]
Hi again,

I read the doc, but I'm trying to do something customized.
I need:
- Something so that I can encode with the PUB public key but can't decrypt the stream with the same PUB key.
- When something is encrypted with the PUB key, it can be decrypted with the PRV private key.

I also need the reciprocity (something encoded with PRV is decryptable by the PUB)

Is it something I can do with your library?

Thanks,

**Comment by jedisct1** [comment]
Encrypting with your own public key is equivalent to symmetric encryption.

So I assume you want to encrypt using another party's public key instead, and that other party will use its private key to decrypt the content.

Use the Noise N variant: https://github.com/jedisct1/libhydrogen/wiki/N-variant to get a shared key. Encrypt using that shared key, and wipe that shared key. That shared key can be later recovered using the initiator's public key and the receiver's secret key.
