### ISSUE TITLE
Bindings

### ISSUE THREAD

**Issue by someburner** [jedisct1/libhydrogen#22]
Hi,

I'm hoping to use libhydrogen for an ESP8266-based project. I have successfully integrated most methods on the ESP, and wrote a C++ utility to sign/encrypt payloads for testing. But now we're working on integration and the lack of php or python bindings is unfortunate. I can probably write a python module, but neither I nor my colleague have experience writing a php extension from scratch. I thought [phosphine](https://github.com/absalomedia/phosphine) would be at least a start, but it appears to be just a skeleton with nothing actually implemented. 

Looking at your other repo [libsodium-php](https://github.com/jedisct1/libsodium-php) it looks like there might be a good amount of overlap in a libhydrogen port. So, is there any effort or plans for a port for libhydrogen?

**Comment by someburner** [comment]
We got something going [here](https://github.com/phplang/hydro.git).

**Comment by jedisct1** [comment]
Oh, wow, this is neat!

Having bindings for all major languages is definitely needed. I started with Rust, but JS and PHP were obviously planned to be next.

PHP is by far the worst language to write bindings for, so I kept postponing it. But indeed, these should be pretty close to the libsodium ones, so quite a lot of code can just be reused.

Thanks for kicking this off!

**Comment by someburner** [comment]
Np! thanks for libsodium + libhydrogen :+1:

**Comment by someburner** [comment]
@jedisct1  - Made some progress on python, it's up here: https://github.com/someburner/pyhy

Only thing I had an issue with so far is cffi not liking `_hydro_attr_warn_unused_result_` and other method attributes. Not a big deal but it would be nice to source the file verbatim, so I'll try to see if there's any way around that that's clean.

**Comment by someburner** [comment]
Added a demo with mqtt: https://github.com/someburner/pyhy/tree/master/demo

far enough to be added to the bindings wiki page?

**Comment by someburner** [comment]
thanks!

**Comment by jedisct1** [comment]
Great work, thank you!

**Comment by jedisct1** [comment]
Awesome! Good luck, Fabian!

**Comment by someburner** [comment]
Me again- I ended up re-writing a bunch of my services in go, so I made go bindings [here](https://github.com/someburner/libhydrogen-go). I'm still sorta new to go, so feedback welcome.

**Comment by nxrighthere** [comment]
@jedisct1 C# wrapper is here https://github.com/nxrighthere/Hydrogen-CSharp ❤️
