### ISSUE TITLE
Code analysis

### ISSUE THREAD

**Issue by nxrighthere** [jedisct1/libhydrogen#31]
I just performed code analysis using PVS-Studio, and the application detected up to 19 warnings with various levels.

Here's a beautiful and convenient HTML report for you:
[libhydrogen_analysis.zip](https://github.com/jedisct1/libhydrogen/files/2709171/libhydrogen_analysis.zip)

**Comment by nxrighthere** [comment]
I believe that there are many false positive warnings, but still, maybe you will find something that deserves some attention.

**Comment by jedisct1** [comment]
Hi, and thanks!

The good news is that these are all false positive, including the "high severity" one (we want to load `x3` and `z3` here).

Thanks!
