### ISSUE TITLE
Minimising header size

### ISSUE THREAD

**Issue by daurnimator** [jedisct1/libhydrogen#35]
Taking a glance at the secret box code, I didn't figure out if `msg_id` and the context are actually taking up 8 bytes of message header.
I'm designing for a situation with very small messages, so header size matters.

**Comment by jedisct1** [comment]
`msg_id` is not present in the header. The context isn't either. These are supposed to be kept in the session state.

Not being present in the header doesn't prevent decryption from failing if incorrect values are being used.

Hope it helps!
