### ISSUE TITLE
How can I derive a master key from a master-master key?

### ISSUE THREAD

**Issue by clintr-at-kornak** [jedisct1/libhydrogen#41]
Hello.  From the wiki page on Password hashing: "Applications can also choose to derive master_key from a master-master key, and a unique user identifier."  How should this be done?  Thanks.

**Comment by jedisct1** [comment]
Hi!

You can use keyed hashing for this:

```c
hydro_hash_hash(master_key, hydro_pwhash_MASTERKEYBYTES,
                user_id, user_id_len, CONTEXT, master_master_key)
```

**Comment by jedisct1** [comment]
Or if your user identifier fits in a 64-bit number, even easier:

```c
hydro_kdf_derive_from_key(master_key, hydro_pwhash_MASTERKEYBYTES, user_id, CONTEXT, master_master_key);
```

**Comment by clintr-at-kornak** [comment]
Thanks for your help
