### ISSUE TITLE
hydro_random_rbit

### ISSUE THREAD

**Issue by temporaryaccount** [jedisct1/libhydrogen#51]
I want to use this library with a STM32 microcontroller which doesn't have an RNG so the suggestion from #40 won't work for me.

For implementing `hydro_random_init` I'm planning to use the ADC values and a counter (like in Arduino variant) driven by LSI clock (LSI has very low accuracy, which is valuable for some randomness).

I want to base my port on Arduino's variant, and something caught my eye. There are no comments so I can't tell whether it's supposed to be this way or this is an error:

```C

static bool
hydro_random_rbit(unsigned int x)
{
    size_t i;
    bool   res = 0;

    for (i = 0; i < sizeof x; i++) {
        res ^= ((x >> i) & 1);
    }
    return res;
}
```

`sizeof` returns the number of bytes, not bits. Maybe this was supposed to be this way:

```C
...
    for (i = 0; i < 8 * sizeof x; i++) {
...
```

BTW, I'm open to suggestions with `hydro_random_init` implementation for RNG-less STM32 if you think that the mentioned approach isn't good enough. Thank you.

**Comment by jedisct1** [comment]
Good catch, thanks!

cf7ca55 fixes this, even though I don't expect any bias from using the two lowest bits.

The same approach should work on STM32, as long as independent timers/counters/interrupts are available.
