### ISSUE TITLE
Small typo in wiki

### ISSUE THREAD

**Issue by nuclearcat** [jedisct1/libhydrogen#58]
https://github.com/jedisct1/libhydrogen/wiki/Public-key-signatures
Using hydro_sign_keygen_deterministic(), the key pair can be deterministically derived from a single key seed (**crypto_sign_SEEDBYTES** bytes).
probably should be:
Using hydro_sign_keygen_deterministic(), the key pair can be deterministically derived from a single key seed (**hydro_sign_SEEDBYTES** bytes).

**Comment by jedisct1** [comment]
Good catch, thanks!
