### ISSUE TITLE
hydro_hash disagrees with the public domain gimli hash when the total input length is an exact multiple of gimli_RATE

### ISSUE THREAD

**Issue by chrisnc** [jedisct1/libhydrogen#61]
It seems that the loop in hydro_hash_update checks whether gimli_RATE bytes have been fed in at the beginning of the loop, rather than the end, resulting in one fewer call to gimli overall if an integer multiple of gimli_RATE bytes are fed into hydro_hash_update, compared with the Gimli_hash function in the Gimli paper. https://gimli.cr.yp.to/gimli-20170627.pdf

**Comment by chrisnc** [comment]
Attaching a log of what happens when I feed the string "test one two" into hydro_hash, compared with feeding the same data (including the prefix and suffix blocks), into Gimli_hash. Before and after each call to gimli I print the state.
[gimli.txt](https://github.com/jedisct1/libhydrogen/files/3333300/gimli.txt)
[hydrogen.txt](https://github.com/jedisct1/libhydrogen/files/3333301/hydrogen.txt)

**Comment by jedisct1** [comment]
Good catch, thank you!
