### ISSUE TITLE
Add Hydride

### ISSUE THREAD

**Issue by gurpreet-** [jedisct1/libhydrogen#70]
Creator of [Lazysodium](https://github.com/terl/lazysodium-java) here. Thank you for creating this library - I love the focus on portability. 

I have created another binding for Java, [Hydride](https://github.com/libly/hydride-java), that works across many platforms running Java.

Please add it to the bindings list. Thank you in advance!

**Comment by jedisct1** [comment]
This is awesome, thank you!

I'm going to add Hydride right away.

**Comment by jedisct1** [comment]
Added, thank you!
