### ISSUE TITLE
tests: failed to build the tests on Windows in Release mode

### ISSUE THREAD

**Issue by myd7349** [jedisct1/libhydrogen#71]
Currently, the test suite uses the `assert` macro to report test results. However, this macro is usually expand to `(void)0` in Release mode. As a result, there will be some warnings:
> c:\users\vcpkg\desktop\libhydrogen\tests\tests.c(125): warning C4101: 'hexf': unreferenced local variable
c:\users\vcpkg\desktop\libhydrogen\tests\tests.c(123): warning C4189: 'b': local variable is initialized but not referenced
c:\users\vcpkg\desktop\libhydrogen\tests\tests.c(121): warning C4101: 'y': unreferenced local variable
c:\users\vcpkg\desktop\libhydrogen\tests\tests.c(169): warning C4101: 'm2': unreferenced local variable
c:\users\vcpkg\desktop\libhydrogen\tests\tests.c(371): warning C4101: 'stored': unreferenced local variable
c:\users\vcpkg\desktop\libhydrogen\tests\tests.c(373): warning C4101: 'static_key': unreferenced local variable

when building in Release mode with MSVC.

Unfortunately, a [```/WX```](https://docs.microsoft.com/en-us/cpp/build/reference/wx-treat-linker-warnings-as-errors?view=vs-2019) option is also specified In `CMakeLists.txt` when using MSVC:
https://github.com/jedisct1/libhydrogen/blob/68e3c591db860e806131d8c1d5ef842674fc87aa/CMakeLists.txt#L81
This option makes MSVC treat all warnings as errors, which, as a result, causes the build failed.

##### How to reproduce?
```
mkdir build
cd build
cmake .. -G "Visual Studio 14 2015"
cmake --build . --config Release
```

I think we may fix this issue in either of these two ways:
1. We define a `assert` likely macro ourselves so that it also works in Release mode. This way, we can also run the tests in Release mode.
    For example, in https://github.com/myd7349/Ongoing-Study/blob/master/c/xassert.h, `xverify` is what we need here.
2. Remove the `/WX` in `CMakeLists.txt`. This fix is short, and that is what I did in https://github.com/microsoft/vcpkg/pull/7436 .

**Comment by jedisct1** [comment]
Thanks!

`NDEBUG` is now unconditionally undefined, in case alternative build systems such as `cmake` define it.

`/WX` has been removed as well.

**Comment by spinda** [comment]
I'm not so sure this is the right fix. What's the value of building the tests in Release mode, if we allow `assert` to turn into `(void)0` in that mode? Then the tests won't actually test anything.

**Comment by jedisct1** [comment]
`NDEBUG` being undefined should be enough to have the `cmake` version behave like the Makefile.
