### ISSUE TITLE
Add Hydride for Android

### ISSUE THREAD

**Issue by gurpreet-** [jedisct1/libhydrogen#75]
Hey, creator of [Lazysodium](https://github.com/terl/lazysodium-java) and [Hydride for Java](https://github.com/libly/hydride-java) here again!

As you can probably tell, I am a big believer in encryption and its value to the world, so I have compiled and created _another_ binding, [Hydride for Android](https://github.com/libly/hydride-android) 🙌. I hope with this new binding, Android users can also benefit from Libhydrogen's capabilities.

Please could you add it to the bindings list? 🙂

**Comment by jedisct1** [comment]
This is fantastic, thank you!
