### ISSUE TITLE
libhydrogen doesn't compile on esp8266 - esp_system.h missing

### ISSUE THREAD

**Issue by ulno** [jedisct1/libhydrogen#79]
Just tried to add libhydrogen to one of my esp8266 projects.

It fails compiling random.h in line 76 as esp_system.h doesn't exist.

AFAIK, this file exists only on ESP32 platforms.
When I comment the #include line, the compilation works, so I assume there is another ``#ifdef ESP32`` needed?

**Comment by jedisct1** [comment]
Hi,

That's very likely.

But even if compilation works, it would be reasonable to take the time to verify that the RNG works as expected.

Unfortunately, the only microcontroller I have is an Arduino, so your help is badly needed :)

**Comment by ulno** [comment]
just providing an empty esp_system.h solves the problem for me now. I will report back with some results soon using libhydrogen on esp8266 soon.
