### ISSUE TITLE
Gimli for short input hashing

### ISSUE THREAD

**Issue by mko-io** [jedisct1/libhydrogen#83]
Hi, I like simplicity of Libhydrogen alot, But I need a short input hashing function for [cuckoo cycle](https://github.com/tromp/cuckoo), it currently use Siphash-2-4 which is available in Libsodium but not Libhydrogen.

My question is is it possible to replace the Siphash with Gimli or a variant of short input hashing function based on gimli permutation?

For my understanding Gimli use only bitwise operation which is more energy efficient and it can utilise general SIMD available in width range of CPU and MCU to  speed up.

thanks

**Comment by jedisct1** [comment]
SipHash is likely to be faster on all platforms. Gimli doesn't need carry propagation, but the number of rounds is unlikely to make it more energy efficient.

For your use case, SipHash-1-3 may be an option.
