### ISSUE TITLE
Noise KK between multiple peers

### ISSUE THREAD

**Issue by Crest** [jedisct1/libhydrogen#90]
I need a one roundtrip handshake like Noise KK for a protocol on top of UDP and have to use a single UDP socket for a lot of reasons. The problem is that Noise KK requires the responder to implicitly know the initiators identity. I worked around this by using Noise N to send the encrypted long term public key along. This works, but requires two public keys (one for N and one for KK) per node which obviously doubles the size of the key material. Is it save to reuse the same key pair for both key exchange variants in this construction or should two key pairs be derived from a single seed?

**Comment by jedisct1** [comment]
Hi Crest,

Using the same public key for both multiple Noise variants should be totally fine.

**Comment by Crest** [comment]
Thanks for answering my question. Using a single longterm keypair for the different Noise variants (N and KK) simplifies my code and the configuration expected of its eventual users.
