### ISSUE TITLE
Decrypt on small targets.

### ISSUE THREAD

**Issue by henrikberg** [jedisct1/libhydrogen#95]
I'm working on a small target that can't use hydro_secretbox_decrypt() since all of the cryptotext is not available at the same time and the resulting plaintext need to be store in flash piece by piece.

I created hydro_secretbox_decrypt_setup(), hydro_secretbox_decrypt_part() and hydro_secretbox_decrypt_final().
It works well as long as long as the length of each part is modulo gimli_RATE (except the last one).

Question:
In hydro_secretbox_xor_dec() is the a reasoning for memcpy() is used in the for loop, but mem_cpy() is used in the leftover part?

If the difference is none I can make hydro_secretbox_decrypt_part() smarter.

I know there is a security problem with this approach, since I need to clear the plaintext manually if the check fails, is there some other reason this is a bad idea?

--HB

**Comment by jedisct1** [comment]
Hi!

They are equivalent.

`memcpy()` is used when the size is a constant, whereas `mem_cpy()` is preferred when the size is not constant (and can possibly be `0`) in order to avoid a function call on some targets.
