### ISSUE TITLE
Support for wasm32-freestanding

### ISSUE THREAD

**Issue by creationix** [jedisct1/libhydrogen#96]
I see there appears to be some support for wasm in the codebase.  I believe it was tested with emscripten.  I would love to use libhydrogen in a wasm based project, but I'm having a very hard time compiling it for the freestanding target using vanilla clang or zig cc.  Most the issues revolve around usage of libc headers and the random sources.

Looking at the supported platforms, I believe it should be possible to support wasm without emscripten's supporting libraries or even needing the wasi runtime.

Am I correct in this assumption?

**Comment by jedisct1** [comment]
Current support is for WASI (it was probably the first library supporting WASI :) ), and it should still compile out of the box using clang with a WASI sysroot.

No emscripten needed.
